# -*- coding: utf-8 -*-
"""Unemploymentrec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mxWI80QF1bxJ8-30rjiL7wnqpfaBmwLp
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import plotly.express as px

df=pd.read_csv("Unemp.csv")

df.head()

df.isnull()

df.columns=['Region','Date','Frequency','Est Unemp Rate','Est Employed','Participation Rate','Area']

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(10,8))
sns.heatmap(df.corr())
plt.show()

df.columns=['Region','Date','Frequency','Est Unemp Rate','Est Employed','Participation Rate','Area']
plt.figure(figsize=(12, 10))
plt.title("Unemployment Record")
#plt.hist(df)
sns.histplot(x="Est Unemp Rate", hue="Region", data=df)
plt.show()

plt.figure(figsize=(12, 10))
plt.title("Indian Unemployment")
sns.histplot(x="Est Unemp Rate", hue="Region", data=df)
plt.show()

unemploment = df[["Region", "Est Unemp Rate"]]
figure = px.sunburst(unemploment, path=["Region", "Est Unemp Rate"],
                     values="Est Unemp Rate",
                     width=700, height=700, color_continuous_scale="RdY1Gn",
                     title="Unemployment Rate in India")
figure.show()

